//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tester.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tester.Languages.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   NEW CARD FOLDER CREATED SUCCESSFULLY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardAddedSuccess {
            get {
                return ResourceManager.GetString("CardAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please add a card first. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardAddError {
            get {
                return ResourceManager.GetString("CardAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This card has already been added. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardExistsWarning {
            get {
                return ResourceManager.GetString("CardExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A CARD FOLDER WITH THE SAME NAME EXISTS\nWOULD YOU LIKE TO OVERWRITE IT? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardFolderExistsWarning {
            get {
                return ResourceManager.GetString("CardFolderExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   THE DEFAULT CARD FOLDER WILL BE DELETED\nDO YOU CONFIRM? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardFolderOverwriteConfirmation {
            get {
                return ResourceManager.GetString("CardFolderOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE ENTER THE CARD NAME. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardNameEmptyError {
            get {
                return ResourceManager.GetString("CardNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Card properties not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardPropertiesNotFoundError {
            get {
                return ResourceManager.GetString("CardPropertiesNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Card properties successfully loaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CardPropertiesSuccess {
            get {
                return ResourceManager.GetString("CardPropertiesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE CHOOSE A CARD. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChooseCardError {
            get {
                return ResourceManager.GetString("ChooseCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a workspace benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ChooseWorkspace {
            get {
                return ResourceManager.GetString("ChooseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add ECU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectAddECU {
            get {
                return ResourceManager.GetString("CreateProjectAddECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added ECU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectAddedECU {
            get {
                return ResourceManager.GetString("CreateProjectAddedECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectBrowseBtn {
            get {
                return ResourceManager.GetString("CreateProjectBrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chooise ECU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectChooiceECU {
            get {
                return ResourceManager.GetString("CreateProjectChooiceECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectDelete {
            get {
                return ResourceManager.GetString("CreateProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECU Information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectECUInfo {
            get {
                return ResourceManager.GetString("CreateProjectECUInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECU Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectECUName {
            get {
                return ResourceManager.GetString("CreateProjectECUName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add a new project benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectLabelAdd {
            get {
                return ResourceManager.GetString("CreateProjectLabelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectProjectName {
            get {
                return ResourceManager.GetString("CreateProjectProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a workspace benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreateProjectWorkspace {
            get {
                return ResourceManager.GetString("CreateProjectWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Project benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePageButton1 {
            get {
                return ResourceManager.GetString("HomePageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Project benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePageButton2 {
            get {
                return ResourceManager.GetString("HomePageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently Created Projects benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePageProjectInfo {
            get {
                return ResourceManager.GetString("HomePageProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePageTreeWievToday {
            get {
                return ResourceManager.GetString("HomePageTreeWievToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Week benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePageTreeWievWeek {
            get {
                return ResourceManager.GetString("HomePageTreeWievWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yesterday benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HomePageTreeWievYesterday {
            get {
                return ResourceManager.GetString("HomePageTreeWievYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid folder path. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidPathError {
            get {
                return ResourceManager.GetString("InvalidPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROJECT SUCCESSFULLY CREATED benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProjectCreatedSuccess {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A FOLDER WITH THE SAME NAME EXISTS\nWOULD YOU LIKE TO OVERWRITE IT? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProjectFolderExistsWarning {
            get {
                return ResourceManager.GetString("ProjectFolderExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE ENTER THE PROJECT NAME. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProjectNameEmptyError {
            get {
                return ResourceManager.GetString("ProjectNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   THE DEFAULT {0} PROJECT WILL BE DELETED\nDO YOU CONFIRM? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProjectOverwriteConfirmation {
            get {
                return ResourceManager.GetString("ProjectOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE FILL OUT ALL FIELDS. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProjectSelectionError {
            get {
                return ResourceManager.GetString("ProjectSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE FILL IN ALL FIELDS benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject1 {
            get {
                return ResourceManager.GetString("warningCreateProject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROJECT CREATED SUCCESSFULLY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject10 {
            get {
                return ResourceManager.GetString("warningCreateProject10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This card has already been added benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject11 {
            get {
                return ResourceManager.GetString("warningCreateProject11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE ENTER THE PROJECT NAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject2 {
            get {
                return ResourceManager.GetString("warningCreateProject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE ENTER THE CARD NAME benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject3 {
            get {
                return ResourceManager.GetString("warningCreateProject3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLEASE SELECT A CARD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject4 {
            get {
                return ResourceManager.GetString("warningCreateProject4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please add a card first benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject5 {
            get {
                return ResourceManager.GetString("warningCreateProject5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A FOLDER WITH THE SAME NAME ALREADY EXISTS\nDO YOU WANT TO OVERWRITE IT? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject6 {
            get {
                return ResourceManager.GetString("warningCreateProject6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DEFAULT CARD FOLDER WILL BE DELETED\nDO YOU CONFIRM? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject7 {
            get {
                return ResourceManager.GetString("warningCreateProject7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW CARD FOLDER CREATED SUCCESSFULLY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject8 {
            get {
                return ResourceManager.GetString("warningCreateProject8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DEFAULT PROJECT WILL BE DELETED\nDO YOU CONFIRM? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string warningCreateProject9 {
            get {
                return ResourceManager.GetString("warningCreateProject9", resourceCulture);
            }
        }
    }
}
